# Generated by Django 3.0.7 on 2024-07-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20240723_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='quantite_commande_avant',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
