# Generated by Django 3.0.7 on 2024-07-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_commande_quantite_commande_avant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Commande'),
        ),
    ]
