# Generated by Django 3.0.7 on 2024-07-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_cart_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='photo',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
