# Generated by Django 3.0.7 on 2024-07-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_produit_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='photo',
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
