# Generated by Django 3.0.7 on 2024-08-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20240725_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_group',
            field=models.CharField(default='', max_length=100),
        ),
    ]
