# Generated by Django 3.0.7 on 2024-08-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_cart_cart_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_group',
        ),
        migrations.AddField(
            model_name='cart',
            name='grouped',
            field=models.BooleanField(default=False),
        ),
    ]
