# Generated by Django 3.0.7 on 2024-08-03 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20240801_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='cart_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
