# Generated by Django 3.0.7 on 2024-08-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_commande_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='num_ordre',
            field=models.CharField(max_length=255),
        ),
    ]
