# Generated by Django 3.0.7 on 2024-08-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20240803_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='num_ordre',
            field=models.IntegerField(),
        ),
    ]
