# Generated by Django 3.0.7 on 2024-08-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20240803_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='num_ordre',
            field=models.CharField(max_length=255),
        ),
    ]
