# Generated by Django 3.0.7 on 2024-08-04 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20240804_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='num_ordre',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
