# Generated by Django 3.0.7 on 2024-08-04 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20240804_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='num_ordre',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commandeavantvalidation',
            name='num_ordre',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
