# Generated by Django 3.0.7 on 2024-08-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20240804_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='raison_refus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
