# Generated by Django 3.0.7 on 2024-08-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_commande_raison_refus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
