# Generated by Django 3.0.7 on 2024-08-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_delete_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
            ],
        ),
    ]
